### ISSUE TITLE
Laravel-permission and laravel-excel

### ISSUE THREAD

**Issue by sebastianbolivart** [spatie/laravel-permission#1556] opened 2020-08-24 19:51 UTC
Hello, i am using your library into a project to manage employees, it's been installed successfully and works fine too, but mi inconvenient appears when i try to use "laravel permission" to create a bulk insert using another library named "laravel excel" that alows me to import data stored in a excel file to my DB. This library works fine too, i don't know wich mistake am i comiting but i am not able to asing a role to users on this bulk insert. ¿Are you able to give me some advice to solve this?. Thanks for your answer, and forgive me if it's a silliness, but i cant find my mistake.

**This is my import file**

```
<?php

namespace App\Imports;

use Spatie\Permission\Models\Role;
use App\User;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Illuminate\Support\Facades\Hash;
use Maatwebsite\Excel\Concerns\WithBatchInserts;
use Maatwebsite\Excel\Concerns\WithChunkReading;
use Spatie\Permission\Models\Permission;

class UsersImport implements ToModel, WithHeadingRow, WithBatchInserts, WithChunkReading
{

  public function model(array $row)
    {
        $user = new User([
          'birthdate'           => $row['birthdate'],
          'name'                       => $row['name'],
          'email'                      => $row['email'],
          'password'                   => Hash::make($row['password']),
          'document_tyep'             => $row['document_tyep'],
          'id_card' => $row['id_card'],
          'telephone'                   => $row['telephone'],
          'address'       => $row['address'],
          'state'    => $row['state'],
          'city'       => $row['city'],
          'employee_state'            => $row['employee_state'],
          'percentage'         => $row['percentage'],
        ]
      );

      $user->assignRole('employee');
      return $user;
    }

    public function batchSize(): int
    {
        return 500;
    }

    public function chunkSize(): int
    {
        return 500;
    }
}
```

**Comment by drbyte** [comment] 2020-08-24 20:54
I'm not sure if the Excel Package (specifically the ToModel trait) does things differently than usual Eloquent operations, however the following probably explains the root cause.

In your code you are calling `new User([$attributes]);` instead of `User::create([$attributes]);`.
`new User()` is essentially `User::make()` which doesn't persist the model, so it has no ID in the database yet, thus the Role cannot be assigned to it.

Two options:
- If you still want to call `new User()` then  first `save()` the `$user` before assigning the role. 
You may need to also call `$user->fresh()` before you can assignRole.
- Usually I would use `User::create([$attributes])` instead of `new User([$attributes])` because `create()` also persists it before returning the completed object. This also avoids needing to call `$user->fresh()` before `assignRole()`.

**Comment by sebastianbolivart** [comment] 2020-08-25 13:24
> 
> 
> I'm not sure if the Excel Package (specifically the ToModel trait) does things differently than usual Eloquent operations, however the following probably explains the root cause.
> 
> In your code you are calling `new User([$attributes]);` instead of `User::create([$attributes]);`.
> `new User()` is essentially `User::make()` which doesn't persist the model, so it has no ID in the database yet, thus the Role cannot be assigned to it.
> 
> Two options:
> 
>     * If you still want to call `new User()` then  first `save()` the `$user` before assigning the role.
>       You may need to also call `$user->fresh()` before you can assignRole.
> 
>     * Usually I would use `User::create([$attributes])` instead of `new User([$attributes])` because `create()` also persists it before returning the completed object. This also avoids needing to call `$user->fresh()` before `assignRole()`.


Thank you so much, my mistake was solved like this. I really appreciate your help.

$user = User::create([
          'birthdate'           => $row['birthdate'],
          'name'                       => $row['name'],
          'email'                      => $row['email'],
          'password'                   => Hash::make($row['password']),
          'document_tyep'             => $row['document_tyep'],
          'id_card' => $row['id_card'],
          'telephone'                   => $row['telephone'],
          'address'       => $row['address'],
          'state'    => $row['state'],
          'city'       => $row['city'],
          'employee_state'            => $row['employee_state'],
          'percentage'         => $row['percentage'],
        ])->assignRole('employee');

**Closed** 2020-08-25 13:24 UTC
Labels: support

**Comment by juanzu** [comment] 2023-01-11 14:05
Hola @sebastianbolivart estoy pasando por lo mismo, realice lo que hiciste y me funciona porque me registra los usuarios con lo roles. Pero hay un problema y es que me guarda los registros en la base de datos pero no me devuelva el mensaje que se importo exitosamente y me devuelvo los mensajes de validación. Sabes algo al respecto ?
