### ISSUE TITLE
PermissionDoesNotExist while Permission actually does exist.

### ISSUE THREAD

**Issue by BjarnBronsveld** [spatie/laravel-permission#231] opened 2017-03-19 16:45 UTC
Hello,

I am trying to implement permissions in my pages to hide menu items, by example. Currently, I am using this:
```
@if(auth()->user()->hasPermissionTo('view_admin_top_menu'))
//content
@endif
```

But it keeps returning the PermissionDoesNotExist exception while I am very sure the permission is in the database. Also, @hasrole() works... so it is very weird to me.

Thanks.

**Comment by drbyte** [comment] 2017-03-19 19:15
Using SequelPro or phpMyAdmin etc, what's the ID number of that `view_admin_top_menu` permission in the database?  

Sorry if this sounds like a basic question: Are you sure there's no typo in its name?

Also, @hasrole() is dealing with roles, not permissions. @can deals with permissions.

**Comment by BjarnBronsveld** [comment] 2017-03-19 19:30
@drbyte I am using Sequel Pro indeed, it has ID 1.

I just found an article saying I have to change my boot() in AuthServiceProvider to:
`
  public function boot(GateContract $gate)
  {
    $this->registerPolicies($gate);

    foreach ($this->getPermissions() as $permission) {
      $gate->define($permission->name, function ($user) use ($permission) {
        return $user->hasPermission($permission);
      });
    }
  }`

in order to make can() work in blade, which didn't work before. Seems to work now :)

**Comment by drbyte** [comment] 2017-03-19 20:15
Hmmm ... `PermissionServiceProvider.php` should take care of that already ...

**Comment by BjarnBronsveld** [comment] 2017-03-19 21:12
The `PermissionServiceProvider.php` is in my `config/app.php`, so that shouldn't be the issue. But I hope it gets solved soon, no hurries for me since it works now :)

**Comment by BjarnBronsveld** [comment] 2017-03-19 23:08
Update: `@can()` now works if a user has the permission, but if the user has a role which has that permission, it doesn't work...

**Comment by eeeeek-da-cat** [comment] 2017-03-21 10:32
I am experiencing similar issues (permissions suposedly not existing, while they are present in DB) since bump to 1.12 ...reverting to 1.11 fixes all issues for me.

**Comment by BjarnBronsveld** [comment] 2017-03-21 11:48
@eeeeek-da-cat Also downgraded to 1.11, fixed it for me too.

**Comment by jdcrecur** [comment] 2017-03-21 12:56
Exact same problem for me. But it definitely has something to do with the caching system within package.

A fresh db migraiton and seed results in everything working fine... continue to develop the app then out of nowhere the permission is gone and the `throw new PermissionDoesNotExist();` is called from `vendor/spatie/laravel-permission/src/Models/Permission.php` @ line 71.

Downgrading to 1.11 to see if the issue presists.

**Comment by otono** [comment] 2017-03-21 18:01
Had the same problem with `$role->givePermissionTo()`. Downgrading to 1.11 helps.

**Comment by komphet5139** [comment] 2017-03-21 23:28
Here is problem file

> vendor/spatie/laravel-permission/src/PermissionRegistrar.php@getPermissions()

I change form
`return $this->cache->rememberForever($this->cacheKey, function () {
            return app(Permission::class)->with('roles')->get();
        });`
To
`return app(Permission::class)->with('roles')->get();`
It's work!

**Comment by BjarnBronsveld** [comment] 2017-03-21 23:31
@komphet5139 I am not going to edit vendor files, if it is the permanent solution, why not add a pull request? 👍

**Comment by AlexVanderbist** [comment] 2017-03-22 09:13
Hi all,

I was looking into this issue but didn't manage to replicate the issue. When creating `Permission`s/`Role`s or assigning them to models the permission cache is automatically cleared... 
The only way I managed to trigger the error was by trying to `givePermissionTo()` with a non-existent permission.

Obviously there is a problem here so if anyone could provide some instructions to replicate the issue starting from a clean Laravel install, that would be great! 

Thanks

**Comment by eeeeek-da-cat** [comment] 2017-03-22 09:54
Create a new project and force it to use 1.11 ... create some permissions and then upgrade to 1.12. Issues started quite soon after upgrading ... maybe even immediately but I noticed after a few hours. I think there is a missmatch with cache keys ... anyway ... succes met oplossen ;)

**Comment by AlexVanderbist** [comment] 2017-03-22 10:56
Hey @eeeeek-da-cat 

I really can't seem to replicate this... Does clearing the cache solve the issue?

**Comment by eeeeek-da-cat** [comment] 2017-03-22 14:42
Hey @AlexVanderbist 

I just did a clean install of my project on my dev-laptop and set my composer.json for 1.12 straight away ... no issues whatsoever (yet) ... somehow there must've been a discrepancy in the cache on upgrading.  I can do some more test scenarios tonight if needed.

**Comment by AlexVanderbist** [comment] 2017-03-22 14:57
That'd be great. I've been messing with it for a while now and I really can't seem to trigger it.

It's probably a discrepancy like you said. If something were to manually update/create a permission/role the cache would be invalid but since it's set never to expire the problem remains...

Maybe we should make cache expiration configurable and set it to 24h by default. This way if something goes wrong at least it'll fix itself. Any thought?

**Comment by drbyte** [comment] 2017-03-22 15:03
> @AlexVanderbist wrote:
> Maybe we should make cache expiration configurable and set it to 24h by default. This way if something goes wrong at least it'll fix itself.

24h is reasonable, even on sites with lots of permissions;  

7d could be used if one still wanted to have the "never expires" mindset.

You could make it a configuration setting, or you could make it a property in the trait, since one can override that in their model.

**Comment by eeeeek-da-cat** [comment] 2017-03-22 15:06
Yeah ... that seems like a good idea. I am quite certain it was the cache since I can't reproduce it when I try it in a blank folder from scratch. Still weird though,  because like you said cache should flush itself, maybe it was a combination of other packages that got updated simultaneous that somehow rendered cache invalid, or permissions still active in session  .... either way ... after a clean setup my project seems to be working fine on 1.12 too.

**Comment by AlexVanderbist** [comment] 2017-03-31 07:32
I've added the `cache_expiration_time` config key in the `v2` branch! Feel free to mess around with it. Release will be in a couple of weeks.

**Comment by Frondor** [comment] 2017-04-03 12:05
Permission cache shouldn't expire until Role model got its permissions updated.

Shouldn't this logic reside on a Model observer? Every time  Role is saved, permission cache should be flushed (simply deleted).

**Comment by AlexVanderbist** [comment] 2017-04-10 15:18
@Frondor there is a model observer for the Role and Permissions models. However updating relations doesn't trigger any of these events, in that case the cache is flushed manually.

In this specific case I think the cache was corrupted at some point in time (maybe by editing db records directly). When updating to 1.12.0 the (corrupt) cache is being used a lot more in the `findByName` method. Downgrading fixed the issue because 1.11.0 didn't use the cache in that crucial place.

I do agree that in an ideal world the cache would only need to be flushed when a model is updated. In practice the cache gets corrupted quite often when people mess around in the database or manually assign permissions or roles.

**Comment by Frondor** [comment] 2017-04-10 15:48
@AlexVanderbist mmm then it could be good to provide artisan commands so users dont mess under any circunstance with DB, and there's no need to create an admin panel.

`php artisan permison:make see_menu`
`php artisan permission:grant see_menu --user=FooUser`
`php artisan permission:grant see_menu --role=BarRole`
`php artisan permission:revoke see_menu --role=BarRole`
`php artisan role:make admin_role`
`php artisan role:grant admin_role --user=FooUser`
`php artisan role:revoke admin_role --user=FooUser`

And we can even make use of CLI i/o to pull  all roles/permissions to set them dinamically... its just an  idea for a feature I think this package lacks

**Comment by AlexVanderbist** [comment] 2017-04-11 09:04
+1 for the commands, sometimes you just want to quickly assign some roles and start using them without having to setup any kind of UI or commands of your own. However I think I'd still quickly edit the DB and flush the cache rather than use the commands. 

On top of that, if your application relies on certain roles and permissions it's probably best to keep them in a seeder anyways to keep them persistent. Imagine cloning the project and having to figure out what permissions and roles you used to recreate them with the commands.

**Comment by Frondor** [comment] 2017-04-11 13:50
@AlexVanderbist you can always `\Artisan::call('role:make admin');` for consistency, which internally does the same than `Role::create()`. I don't know but if I must create an ui for permission management I'd use the commands and leverage the logic to this package.

**Comment by archy-bold** [comment] 2017-04-21 08:47
I have the same issue.

Downgrading to 1.11 only works for `$user->hasPermissionTo($permName)` and not for `$user->can($permName)`. I add my permissions to roles with database seeds that simply inserts with the `DB` facade:

```
DB::table('permissions')->insert([
    'name' => $permName,
]);
```

Is there something wrong with doing it that way?

I managed to fix the issue by running `php artisan cache:clear` but how can I prevent the cache going out of sync?

**Comment by AlexVanderbist** [comment] 2017-04-21 09:06
@archy-bold All methods to manage permissions/roles the package provides will take care of the cache for you.

However when you change the database manually (for example through seeds), you'll have to flush the cache yourself. Nothing wrong with that, just something to keep in mind.

**Comment by archy-bold** [comment] 2017-04-21 09:08
Ah cool, so provided I run `php artisan cache:clear` after every `php artisan db:seed` I'll be ok?

**Comment by AlexVanderbist** [comment] 2017-04-21 09:55
@archy-bold yep, if you don't want to lose the rest of your cache every time you can use `php artisan cache:forget spatie.permission.cache` as well. That'll only clear the cache for this package.

**Closed** 2017-04-24 08:44 UTC

**Comment by aliworkshop** [comment] 2017-07-10 13:20
go to vendor/spatie/laravel-permission/src/Models/Permission.php
in line 80 
remove  :
        $permission = static::getPermissions()->where('name', $name)->where('guard_name', $guardName)->first();

replace :
        $permission = Permission::where('name', $name)->where('guard_name', $guardName)->first();

problem will be solved

**Comment by rizerzero** [comment] 2017-10-21 19:01
and other reason could be adding manually a permission on the tabel  never forget to user 
##forgetCachedPermissions method

**Comment by EngEryx** [comment] 2018-06-25 15:00
I solved my case by first querying and passing the instance of that model to the $user->givePermissionTo ...

**Comment by Longhot** [comment] 2018-08-28 13:32
php artisan make:auth

**Comment by agsachdev** [comment] 2019-10-05 06:02
> go to vendor/spatie/laravel-permission/src/Models/Permission.php
> in line 80
> remove :
> $permission = static::getPermissions()->where('name', $name)->where('guard_name', $guardName)->first();
> 
> replace :
> $permission = Permission::where('name', $name)->where('guard_name', $guardName)->first();
> 
> problem will be solved

It's working perfectly :-)

**Comment by cesarcruzc** [comment] 2020-03-27 08:11
https://stackoverflow.com/a/51637387/4009756
