### ISSUE TITLE
redirect authentificated users to different pages by role using breeze authentification

### ISSUE THREAD

**Issue by manelbenmiled** [spatie/laravel-permission#2199] opened 2022-10-03 13:37 UTC
### Discussed in https://github.com/spatie/laravel-permission/discussions/2198

<div type='discussions-op-text'>

<sup>Originally posted by **manelbenmiled** October  3, 2022</sup>
hi,
i want to redirect users authentificated to specific pages after login 

**NB**: i assign role to every user that is connected and i'm using Active Directory to login 

**LoginController:**
`protected $redirectTo = RouteServiceProvider::HOME;`

**RouteServiceProvider**
`public const HOME='/';`

How can i set up this please?</div>

**Comment by erikn69** [comment] 2022-10-03 13:44
Duplicate of #2197

**Comment by manelbenmiled** [comment] 2022-10-03 13:51
yes it is my question in the discussion i didn't find any solution so made it like issue

**Comment by erikn69** [comment] 2022-10-03 13:52
https://github.com/spatie/laravel-permission/discussions/2198#discussioncomment-3787509

**Comment by manelbenmiled** [comment] 2022-10-04 09:17
i fixed it, thanks for your help.

**AuthenticatedSessionController :**

```
public function store(LoginRequest $request)
{
        $request->authenticate();

        $request->session()->regenerate();

       if(Auth::user()->hasRole('show_list103')){
            return redirect()->route('list103');
        }else if(Auth::user()->hasRole('show_list950')){
            return redirect()->route('list950');
        }else{
            return redirect()->route('list');
        }

        //return redirect()->intended(RouteServiceProvider::HOME);
 }
```

**LoginController:**

 ```
   protected function authenticated(Request $request, $user)
    {
         if($user->hasRole('show_list103')){
            return redirect()->route('list103');
        }else if($user->hasRole('show_list950')){
            return redirect()->route('list950');
        }else{
            return redirect()->route('list');
        }
    }
```

**Closed** 2022-10-04 09:18 UTC
