### ISSUE TITLE
Duplicate entry '3-f13b191c-426c-4b03-ae29-43005e0b7a4b-App\\Models\\User' for key 'PRIMARY'"

### ISSUE THREAD

**Issue by LrMiLoef** [spatie/laravel-permission#1986] opened 2022-01-05 12:52 UTC
I created a single page application that communicates with a laravel api. 
in the backend i hooked in the `AuthSuccessFull`-Event to update the assigned roles of the user who sends the request.
When i test this with insomnia or postman, everything works fine but when the SPA sends many requests to the api, it happens that i get following error: `"Duplicate entry '3-f13b191c-426c-4b03-ae29-43005e0b7a4b-App\\Models\\User' for key 'PRIMARY'"`

in my application i'm using `$user->syncRoles()` for refreshing the roles.

i think the problem here is "parallel processing". It can be, that one request just adds the roles to a user, while another parallel request also tries to add them. Then i'll get this conflict. 

The question is: how can i avoid this? can i "lock" the execution of syncRoles? Or do you have an other approach to solve that problem?

**Comment by erikn69** [comment] 2022-01-05 13:39
Question for [Laravel Framework](https://github.com/laravel/framework)
[pessimistic-locking](https://laravel.com/docs/8.x/queries#pessimistic-locking)
[how-to-lock-table-with-laravel](https://newbedev.com/how-to-lock-table-with-laravel)

**Comment by freekmurze** [comment] 2022-01-19 08:16
Question is out of scope for this package.

**Closed by freekmurze** 2022-01-19 08:16 UTC

**Comment by samuelhgf** [comment] 2024-03-15 15:52
Having the same issue here

**Comment by drbyte** [comment] 2024-03-15 18:42
@samuelhgf wrote:
> Having the same issue here

It is likely that your problem is rooted in your Laravel application, not in this package.
However, if you believe the problem is with this package, please open a new issue showing enough code that we can replicate it, in order to fix it.
