### ISSUE TITLE
Help!! Spatie Permissions with Laravel Breeze

### ISSUE THREAD

**Issue by devhoussam** [spatie/laravel-permission#1652] opened 2021-01-04 21:29 UTC
![GitHub Logo](https://i.imgur.com/7qERJOF.png)

[Gist - What I already made need help on it to achieve this](https://gist.github.com/devhoussam/1feef5e279b8acfc039d9d593740bdb6)

**app\Http\Controllers\Auth\RegisteredUserController.php**

```
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Providers\RouteServiceProvider;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RegisteredUserController extends Controller
{
    /**
     * Display the registration view for student.
     *
     * @return \Illuminate\View\View
     */
    public function createStudent()
    {
        return view('auth.student-space');
    }
	
    /**
     * Display the registration view for instructor.
     *
     * @return \Illuminate\View\View
     */
    public function createInstructor()
    {
        return view('auth.instructor-space');
    }

    /**
     * Handle an incoming registration request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     *
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|confirmed|min:8',
        ]);

        Auth::login($user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]));
		
		// Create roles
		
		$role = Role::create(['name' => 'student']);
		$role = Role::create(['name' => 'instructor']);
		
		// Assigning roles
		
		auth()->user()->assignRole([$role]);
		
		// Check if it's correct roles
		
		if(auth()->user()->hasRole('student')) {
			return redirect()->intended('/student/dashboard');
		} else if (auth()->user()->hasRole('instructor')) {
			return redirect()->intended('/instructor/dashboard');
		} else {
			return redirect()->back();
		}
		
		event(new Registered($user));
    }
}
```

**app\routes\auth.php**

```
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\RegisteredUserController;

Route::get('/student-space', [RegisteredUserController::class, 'createStudent'])->middleware('guest')->name('student-space');

Route::get('/instructor-space', [RegisteredUserController::class, 'createInstructor'])->middleware('guest')->name('instructor-space');
```

**Comment by drbyte** [comment] 2021-01-04 23:08
Duplicate of #1648 
Best to keep the discussion in one place.

**Closed by drbyte** 2021-01-04 23:08 UTC
Labels: laravel-use
