### ISSUE TITLE
Access to undeclared static property Spatie\Permission\PermissionRegistrar::$pivotRole

### ISSUE THREAD

**Issue by moijafcor** [spatie/laravel-permission#2578] opened 2023-12-13 00:28 UTC
**Describe the bug**

` Access to undeclared static property Spatie\Permission\PermissionRegistrar::$pivotRole`

blames

```
# xxxx_xx_xx_xxxxxx_create_permission_tables.php

6▕  use Spatie\Permission\PermissionRegistrar;

....

88▕             $table->unsignedBigInteger(PermissionRegistrar::$pivotRole);

```
defined in:

```
class PermissionRegistrar
{

    ....
    public string $pivotRole;
    .....

```

**Versions**

```
laravel/framework                  v10.37.1 The Laravel Framework.
spatie/laravel-permission          6.2.0    Permission handling for Laravel 8.0 and up
```

*** Environment ***

```
  Laravel Version .......................................................................................................................... 10.37.1  
  PHP Version ............................................................................................................................... 8.1.13  
  Composer Version ........................................................................................................................... 2.4.4  
```

*** Database version: ***

`MySQL 8`

**Comment by drbyte** [comment] 2023-12-13 02:55
Duplicate of #2577.

**Closed by drbyte** 2023-12-13 02:55 UTC
Labels: duplicate
