### ISSUE TITLE
Assign permissions to Pivot Table 

### ISSUE THREAD

**Issue by sys-auditing** [spatie/laravel-permission#1667] opened 2021-01-14 14:52 UTC
Hi, how to Use Spatie Laravel-permission Package for Pivot Table ?

**Comment by erikn69** [comment] 2021-02-08 22:13
You just have to add a pivot on the tables "roles" and "model_has_permissions", and then overwrite the relationship in the User model "public function roles(): MorphToMany" and "permissions(): MorphToMany", i use session for save the new pivot on login, and later i use the session function for add the pivot on user relationship with whereraw, is that what whas loking for?

**Comment by kaaaaaaaaaaai** [comment] 2021-07-05 05:04
@erikn69 
I'm stuck with the same problem.
Could you please tell me more about it?

**Comment by erikn69** [comment] 2021-07-05 14:33
@kaaaaaaaaaaai  add a pivot field, and on login authenticated i put that id on session
![image](https://user-images.githubusercontent.com/4933954/124485150-e5b7c100-dd71-11eb-9258-dc396b84d88d.png)

Now overwrite relations on user model and add a where for session id
**ROLES:**
https://github.com/spatie/laravel-permission/blob/a6e4122b65094baba7f98df153af0768ef910c85/src/Traits/HasRoles.php#L37-L49
```php
public function roles(): BelongsToMany
    {
        return $this->morphToMany(
            config('permission.models.role'),
            'model',
            config('permission.table_names.model_has_roles'),
            config('permission.column_names.model_morph_key'),
            'role_id'
        )->where(config('permission.table_names.model_has_roles').'.empr_id',session('empr_id'));
    }
```
**Permissions**
https://github.com/spatie/laravel-permission/blob/a6e4122b65094baba7f98df153af0768ef910c85/src/Traits/HasPermissions.php#L40-L52
```php
public function permissions(): BelongsToMany 
     { 
         return $this->morphToMany( 
             config('permission.models.permission'), 
             'model', 
             config('permission.table_names.model_has_permissions'), 
             config('permission.column_names.model_morph_key'), 
             'permission_id' 
         )->where(config('permission.table_names.model_has_permissions').'.empr_id',session('empr_id')); 
     } 
```
Now works with a pivot id based on session, with that example also you can made custom roles for each pivot id

**Comment by erikn69** [comment] 2021-07-05 15:36
And maybe duplicate of [#1634](https://github.com/spatie/laravel-permission/issues/1634)

**Closed** 2021-07-08 14:16 UTC
Labels: help wanted, laravel-use
