### ISSUE TITLE
Role Hierarchy Level - v3?

### ISSUE THREAD

**Issue by starnetwork** [spatie/laravel-permission#767] opened 2018-06-11 17:47 UTC
Hello,
about Role Hierarchy Level
Issue #512 
it's plan to be in v3?
any estimate time for that release?

Thanks!

**Comment by lucasdcrk** [comment] 2018-06-21 19:37
See **https://github.com/spatie/laravel-permission/issues/685**

**Comment by drbyte** [comment] 2018-08-01 22:51
Closing, because this is a duplicate of other open issues.

**Closed** 2018-08-01 22:51 UTC
Labels: duplicate
