### ISSUE TITLE
Please help me with this test!

### ISSUE THREAD

**Issue by larsjanssen6** [spatie/laravel-permission#338] opened 2017-06-27 15:14 UTC
Hi,

Awesome package! In my WebApp it's working but my test keeps failing. Could you please take a quick look? Would really appreciate that!

**Test:**

```
/** @test */
public function a_user_with_right_permission_can_update_company_profile()
{
    $permission = create(Permission::class, ['name' => 'bewerk-bedrijf-instellingen']);
    $role = create(Role::class, ['name' => 'super-admin']);

    $role->givePermissionTo($permission->name);
    $user = create(User::class)->assignRole($role->name);

    $user = $user->fresh();

    $this->signIn($user);

    $settings = [
        'name'          => 'Company',
        'email'         => 'info@company.com',
        'phone'         => '0623844932',
        'website'       => 'http://www.domain.com',
        'description'   => 'A short description',
    ];

    $this->patch('/instellingen/bedrijf/profiel', $settings)
        ->assertSessionHas('status', 'Bedrijfsprofiel geupdatet!');

    $this->assertDatabaseHas('settings', $settings);
}
```

**Controller:**

```
public function __construct()
{
    $this->middleware('permission:bewerk-bedrijf-instellingen');
}
```

**Middleware (permission):**

```
if (!$request->user()->hasPermissionTo($permission)) {
    return back()
        ->with('status', 'Niet geautoriseerd!');
}

return $next($request);
```

Result is always:

```
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Bedrijfsprofiel geupdatet!'
+'Niet geautoriseerd!'
```

Already asked it <a href="https://laracasts.com/discuss/channels/laravel/spatie-permission-package-testing">here</a> on Laracasts.  Really need some help here!

Maybe it's a cache issue? 

Thanks !

**Comment by freekmurze** [comment] 2017-06-27 21:52
On first sight I don't see the cause of the problem.

I'd put some `dd` statements in that middleware to check if there is a logged in user, and take a look at which permissions it has there.

Closing this as this problem is probably related to your app and not to this package.

**Closed by freekmurze** 2017-06-27 21:52 UTC
