### ISSUE TITLE
Cannot assign Role from a specific guard 

### ISSUE THREAD

**Issue by raftalks** [spatie/laravel-permission#565] opened 2017-11-18 18:15 UTC
I have come across this issue where I want to seed in roles and assign them to generated user, and in my case the role is created with a guard name. I am not clear how to assign that role to an instance of user model using assignRole method. Since my default guard is web and not the custom one, I need to assign role from a different guard to the user inside the seeder. I hope I have explained the issue clearly. To explain in detail, here is the tinker output from:

<img width="648" alt="spatie-laravel-permission-error" src="https://user-images.githubusercontent.com/788192/32983423-2a244b68-ccb6-11e7-9910-2f6e10939b3e.png">

is there a way to handle this?

**Comment by introwit** [comment] 2017-11-20 07:02
@raftalks Hi :) We have a good documentation around the use of guards with this package [here](https://github.com/spatie/laravel-permission#usage) Hope that helps, let me know if that still doesn't solve your problem :)

**Comment by raftalks** [comment] 2017-11-20 07:35
@introwit the documentation only shows how to create roles and permissions under multiple guards, but one can't assign a user with a role or permission giving a a specific guard.

**Comment by introwit** [comment] 2017-11-20 07:41
@raftalks so the role `root` belongs to the guard `console` but you want to assign that role `root` to the `User` and the `User` belongs to a different guard than `console`?

**Comment by raftalks** [comment] 2017-11-20 07:42
When seeding a user, I am creating the roles under certain guard and don't see any way I can assign the roles for a user instance created when seeding.

When I do try to assign a role, it seems this library is looking for the roles under default guard. This doesn't work well if I have different guards for different resources of an API, where users are not strictly set for a specific guard

**Comment by raftalks** [comment] 2017-11-20 07:51
@introwit In my current project, I am assuming I can use this library to set roles and permissions by different guards set to different resources. Lets say, I am simply using the same User Providers under each of the custom guards set on my Laravel project.

```
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],
        'console' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],

      // ... some more custom guards
    ],
```

and then I have route groups with middleware set to work with auth:console, auth:api, etc.

Tell me if this approach is wrong for using custom guard roles and permissions, the idea I had in mind was that I can set separate set of roles and permissions based on which guard the user have used to access the resource.

The issue I am facing is at the time of assigning Roles from a custom guard to a generated user account, such as when using Seeder, it is trying to find the role from the default guard which is web on my application.

am I doing this wrong?

**Comment by introwit** [comment] 2017-11-20 08:20
@raftalks what I would do in such situation is create different providers for each guard especially when there is authorization to manage too. From the package point of view of assigning roles from a custom guard to a user, it would be nice to have @freekmurze 's thoughts on it :)

**Comment by the94air** [comment] 2017-11-21 22:40
I had the same problem but I solved it by implementing Role or Permission models to my app and every thing is working fine.
https://github.com/spatie/laravel-permission#extending

**Comment by AlexVanderbist** [comment] 2017-11-23 09:42
Hi @raftalks, when you try to assign a permission to one of your `$user`a, the package doesn't know what guard this `$user` is using. In this case it'll try to look for the permission or role in the first guard (in this case `web`) and not find the given `console` permission. 

You could solve this (as @introwit suggested) by using different models and different providers for these different types of users. They could still all extend the same `User` class.

**Comment by c00p3r** [comment] 2017-11-24 17:47
Hi everyone!
Stumbled upon same stuff as @raftalks.
Don't wanna write my own user provider (that's not simple you know...)
And I just can't use another model (because project is already running live)
So any other suggestions? (besides writing own method instead "assignRole" and "getStoredRole")
@the94air could you share your solution, please?
@raftalks have come up with smthn?

**Comment by c00p3r** [comment] 2017-11-24 18:04
Here's what I've came up with (don't throw rocks on me):
````
public function assignRole($roles, string $guard = null)
    {
        $roles = \is_string($roles) ? [$roles] : $roles;
        $guard = $guard ? : $this->getDefaultGuardName();

        $roles = collect($roles)
            ->flatten()
            ->map(function ($role) use ($guard) {
                return $this->getStoredRole($role, $guard);
            })
            ->each(function ($role) {
                $this->ensureModelSharesGuard($role);
            })
            ->all();

        $this->roles()->saveMany($roles);

        $this->forgetCachedPermissions();

        return $this;
    }

    protected function getStoredRole($role, string $guard): Role
    {
        if (\is_string($role)) {
            return app(Role::class)->findByName($role, $guard);
        }

        return $role;
    }
````
Usage:
````
$user->assignRole('admin'); // guard will be default
$user->assignRole('admin', 'api'); // explcitly setting the guard
````
And it kinda works...
Waiting for your comments...

**Comment by the94air** [comment] 2017-11-24 18:07
At first I got the same exception but after making my own model every thing is working.
```php
<?php
// App\Permission

namespace App;

use Spatie\Permission\Contracts\Permission as PermissionInterface;
use Spatie\Permission\Models\Permission as PermissionModel;
use Illuminate\Database\Eloquent\Model;

class Permission extends PermissionModel implements PermissionInterface
{
    protected $guard_name = 'admin';
}
```
```php
<?php
// App\Role

namespace App;

use Spatie\Permission\Contracts\Role as RoleInterface;
use Spatie\Permission\Models\Role as RoleModel;
use Illuminate\Database\Eloquent\Model;

class Role extends RoleModel implements RoleInterface
{
    protected $guard_name = 'admin';
}
```

**Comment by c00p3r** [comment] 2017-11-27 09:29
@the94air  so you're using only one guard 'admin'?
What I'm after is some universal/general solution

**Comment by c00p3r** [comment] 2017-11-27 09:32
Also we could construct Role/Permission models with current guard:
_file spatie/laravel-permission/src/Models/Role.php_
````
class Role extends Model implements RoleContract
{
    use HasPermissions;
    use RefreshesPermissionCache;

    public $guarded = ['id'];

    public function __construct(array $attributes = [])
    {
        // my code
        if (empty($attributes['guard_name'])) {
            $guards = array_keys(config('auth.guards'));
            foreach ($guards as $guard) {
                if (Auth::guard($guard)->check()) {
                    $attributes['guard_name'] =  $guard;
                }
            }
        }
        // my code end

        $attributes['guard_name'] = $attributes['guard_name'] ?? config('auth.defaults.guard');

        parent::__construct($attributes);

        $this->setTable(config('permission.table_names.roles'));
    }
...
````

**Comment by the94air** [comment] 2017-11-27 10:59
I think that will do the same. Is it fixed now?

**Comment by c00p3r** [comment] 2017-11-27 11:22
@the94air if you use only one guard then you're kinda off-topic here. Because the issue is in that when you use 2 or more guards in your app, you can't assign roles for other guards except default one

**Comment by c00p3r** [comment] 2017-11-27 11:25
I believe I'll make a PR and see what core dev team say

**Comment by c00p3r** [comment] 2017-11-27 13:07
what I've found also is that `hasRole` method won't even check if role assigned for specific guard

**Comment by c00p3r** [comment] 2017-11-28 09:18
@AlexVanderbist u said: 
> You could solve this by using different models
so I'll need 2 separate DB tables (like api_users, web_users)?

**Comment by doghap** [comment] 2017-12-01 10:32
i have the same issure here. but add a new function `$user->assignRole('admin', 'api');` is not a good solution, because u will meet another problem: middleware. the permission middleware uses the function `registerPermissions()` in `PermissionRegistrar.php`. u cant  pass your guard name to that function (i think its impossible), so it will use the default guard too. what you need todo is set table, primaryKey attributes and set the foreignkeys to `user_id` in your relationship functions. just like this.
 ```
class User extends Authenticatable
{

    use HasApiTokens, HasRoles;

    protected $table = 'users';

    protected $primaryKey = 'id';

	public function merchant() {
		return $this->hasOne(Merchant::class, 'user_id');
	}
}

and extend user model:

class MerchantUser extends User {
	protected $guard_name = 'merchant';
}

you maybe want to set your guard's provider's model to MerchantUser in auth.php.

**Comment by c00p3r** [comment] 2017-12-01 16:16
@doghap you are right
but I solved only the issue with 'assigning' role to guard
NOT checking it via middleware

It is impossible to check role with specific guard in middlewares
BUT it is possible to do that inside your controller methods
so this solution might help a bit to someone

**Comment by c00p3r** [comment] 2017-12-01 16:18
@doghap making separate models (providers) for each guard is another solution too

**Comment by AlexVanderbist** [comment] 2017-12-05 10:08
>It is impossible to check role with specific guard in middlewares
BUT it is possible to do that inside your controller methods
so this solution might help a bit to someone

You could also write a custom middleware that does the same thing as the `HasRole` middleware but with your custom guard hardcoded in there. 

Can this issue be closed?

**Comment by c00p3r** [comment] 2017-12-06 09:11
I think this should be closed
Especially after reading https://github.com/spatie/laravel-permission/issues/479

**Closed** 2017-12-06 09:18 UTC
