### ISSUE TITLE
Add a custom properties column

### ISSUE THREAD

**Issue by lucasdcrk** [spatie/laravel-permission#766] opened 2018-06-11 15:50 UTC
Hi!

I'd really like to have a json custom properties column for each roles, so I can associate a role to a color for exemple.

**Comment by Nowi5** [comment] 2018-07-17 15:26
Yes you can do. Just run a migration after installing Spatie which add the column. Define your own model, set the config right and done. I use this to have a role description.

**Comment by drbyte** [comment] 2018-08-01 22:55
Closing because this is essentially a duplicate of #670

**Closed by drbyte** 2018-08-01 22:55 UTC
Labels: enhancement

**Comment by HakerTag** [comment] 2021-08-23 16:32
https://spatie.be/docs/laravel-permission/v4/advanced-usage/extending
