### ISSUE TITLE
No query results for model

### ISSUE THREAD

**Issue by sajadabs** [spatie/laravel-permission#1713] opened 2021-03-26 13:48 UTC
Hi, I install this package and when i want give permission to role or assign a role to user laravel throw me this exception :
"message": "No query results for model [Spatie\\Permission\\Models\\Role] admin",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
    "file": "D:\\...\\...\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php",
    "line": 381,
thanks for helping me.

**Comment by drbyte** [comment] 2021-03-26 18:50
There's not enough information in your post to provide any assistance in debugging the errors in your application code.

**Comment by sajadabs** [comment] 2021-03-26 19:28
Thank you for your response.
Here are my routes for roles and permissions

` Route::get('roles', 'PermissionController@role_list');
        Route::post('roles', 'PermissionController@role_store');
        Route::get('permissions', 'PermissionController@permission_list');
        Route::post('permissions', 'PermissionController@permission_store');
        Route::post('rolepermissions/{role}', 'PermissionController@role_has_permissions');
        Route::post('assignuserrole/{role}', 'PermissionController@assign_user_to_role');`

My problem is with the last two routes and other routes are working.
When i want give permission to role ->    Route::post('rolepermissions/{role}', 'PermissionController@role_has_permissions');
And when i want assign role to user ->  Route::post('assignuserrole/{role}', 'PermissionController@assign_user_to_role');

Here my role_has_permissions function:

`public function role_has_permissions(Request $request,Role  $role)
    {
        $validator = Validator::make($request->all(), [
            'permission_id' => 'required|exists:permissions,_id'
        ]);
        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()], 401);
        }
        $permission = Permission::find($request['permission_id'])->firstOrFail();
        if ($role->givePermissionTo($permission)) {
            return response()->json(['success' => $role], $this->successStatus);
        }
    }`

and my assign_user_to_role function:

`public function assign_user_to_role(Request $request, Role $role)
    {
        $validator = Validator::make($request->all(), [
            'user_id' => 'required|exists:users,id'
        ]);
        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()], 401);
        }
        $user = User::find($request['user_id'])->firstOrFail();
        if ($user->assignRole($role)) {
            return response()->json(['success' => $user], $this->successStatus);
        }
    }`

And also at the beginning of the controller i have :

`use App\Models\User;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;`

And finally, when I use these functions, that error is displayed to me!!!
Now I do not understand exactly what is happening and I need help.
Thank you for helping me.

**Comment by drbyte** [comment] 2021-03-26 19:31
Tip: Markdown syntax for github: https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by drbyte** [comment] 2021-03-26 19:44
> "message": "No query results for model [Spatie\Permission\Models\Role] admin",
"exception": "Symfony\Component\HttpKernel\Exception\NotFoundHttpException",

I think this is caused by route-model-binding in `assignuserrole/{role}` and `rolepermissions/{role}` where in your controller methods you're receiving `Role $role` as a bound-and-resolved parameter.

What is `$role` resolving to in those controller methods? 
The error message you quoted seems to be passing a string, but route-model-binding is based on the ID number.

**Comment by sajadabs** [comment] 2021-03-26 20:25
Oh really thank you I thought it works by name I really thank you for all your tips.

**Closed** 2021-03-27 06:04 UTC
