### ISSUE TITLE
The permission check inside the package does not work

### ISSUE THREAD

**Issue by kvinkinamoto** [spatie/laravel-permission#1942] opened 2021-11-26 11:20 UTC
I have two projects. One in which I develop a package another in which I use this package. Where I develop and from not connected with git 
![composer dev](https://user-images.githubusercontent.com/1387047/143572399-c873f63e-2a63-4879-9182-597e4c0be53d.png)
check of permissions
       auth()->user()->cannot('cache_show_admin_menu') 
 works correctly. 

And in the project where it is connected from the git
![composer proj](https://user-images.githubusercontent.com/1387047/143572499-174a3b92-a6e7-4aa7-938e-a8598963b282.png)
, the rights check auth()->user()->cannot('cache_show_admin_menu')  always gives false

You can use `composer show` to get the version numbers of:
- spatie/laravel-permission package version: 5,4
- illuminate/framework package 8.65

PHP version:
8.0
Database version:
any

Steps to reproduce the behavior: dicribe up

Here is my example code and/or tests showing the problem in my app: The company's policy prohibits open source

- OS: [e.g. Windows 10]

**Comment by kvinkinamoto** [comment] 2021-11-26 14:27
the only difference is the connection in the compositor
if you transfer the package to the project and connect as a type of path everything works. I found out that there was a problem with Laravel's guards. Spati test methods work approx. But the gates of Laravel do not tighten

**Comment by angeljqv** [comment] 2021-12-17 14:53
Duplicate of #1941

**Comment by freekmurze** [comment] 2022-01-19 08:17
Duplicate of discussion.

**Closed by freekmurze** 2022-01-19 08:17 UTC
