### ISSUE TITLE
We are not able to check the permission of the logged in user

### ISSUE THREAD

**Issue by gurpals** [spatie/laravel-permission#1711] opened 2021-03-26 11:58 UTC
We are using Spatie with Laravel 5.8 and it was working fine with php 7.1 and ubuntu 18.04

Now, we moved the website to new server which is having php 7.4 and ubuntu 20.04

Here is the code which we are using int he middleware:

if (app('auth')->user()->can($permission)) {
    return $next($request);
}

We are passing $permission = 'manage accounts';

And user is also having this permission but still it returns: bool(false)

Earlier it was working fine on previous server. Please help.

**Comment by drbyte** [comment] 2021-03-26 19:01
You seem to suggest that the problem is because you changed servers, implying that either the PHP or Ubuntu version may be the cause.
I'm not convinced that those are the contributors of the problem.
It seems like something else has changed, such as other things in your application or configuration, or maybe you've updated package dependencies to newer versions and things have changed, etc.

However, you probably need to troubleshoot your middleware. 
Factors to consider:
- what user is it actually resolving?
- is a user actually resolved at all?
- does using `$request->user()` give the same result as your current app('auth')->user() code?
- does using `hasPermissionTo()` instead of `can()` make any difference?

**Closed** 2021-05-06 15:35 UTC
