### ISSUE TITLE
hasPermission('perm') return error when perm doesn't exist 

### ISSUE THREAD

**Issue by AEK-BKF** [spatie/laravel-permission#33] opened 2016-01-07 10:09 UTC
I have this code :
return User::find($id)->hasPermission($permission);
It returns true if $permission exists, and this error when not :
ErrorException in HasRoles.php line 174: Trying to get property of non-object

Please Help me

**Comment by freekmurze** [comment] 2016-01-10 00:36
Fixed in v1.3.1

**Closed by freekmurze** 2016-01-10 00:36 UTC

**Comment by AEK-BKF** [comment] 2016-01-10 07:50
It does not work with me, but I edited hasRoles class like this :
 public function hasDirectPermission($permission)
    {...}
and 
protected function hasPermissionViaRole($permission)
    {...}
and it works fine :)
Thanks.

**Comment by freekmurze** [comment] 2016-01-10 11:39
I can't reproduce this. In your first example, is `$permission` a string?

**Comment by AEK-BKF** [comment] 2016-01-10 11:47
Yes !

**Comment by freekmurze** [comment] 2016-01-10 11:55
Here is [the test that handles your case](https://github.com/spatie/laravel-permission/blob/master/tests/HasRolesTest.php#L105). It seems to work.

Could you please create a failing test?

**Comment by AEK-BKF** [comment] 2016-01-10 12:04
When I set :
protected function hasDirectPermission(Permission $permission)
I get this error :
Call to undefined method Illuminate\Database\Query\Builder::hasDirectPermission() 
When I set this :
public function hasDirectPermission(Permission $permission)
I get :
ErrorException in HasRoles.php line 168: Argument 1 passed to App\Models\User::hasDirectPermission() must implement interface Spatie\Permission\Contracts\Permission, string given

**Comment by freekmurze** [comment] 2016-01-11 18:40
`hasDirectPermission` isn't supposed to be called from your application code. That's why it's protected.
